# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


jobs:
- job: PopoTestPageFlow
  pool:
    vmImage: 'vs2017-win2016'
#    vmImage: 'Ubuntu 16.04'

  steps:
  - script: ls
    displayName: ls command
  - task: Maven@3
    displayName: Maven Package
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      goals: 'clean -DskipTests=true package'

  - script: ls
    displayName: ls command
  - script: ls build/
    displayName: ls 'build' foler command
  - script: java -jar build/flow-page-tests.jar --xml testng.xml --cl TestPage --pr=name=JAR
    displayName: java -jar
  - script: ls build/
    displayName: ls 'build' foler command
  - script: echo ${Build.testng.xml}
  - script: echo ${build.testng.xml}
  - script: echo ${Agent.OS}
  - script: echo ${Build.ArtifactStagingDirectoryd}
    displayName: Variables



#  - task: PublishBuildArtifacts@1
#    displayName: Publish Build Artifacts
#    inputs:
#      PathtoPublish: '$(System.DefaultWorkingDirectory)'
#      name: 'drop'

