# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
- job: PopoTestPageFlow
  pool:
    vmImage: $(vmImageVar)
#    vmImage: 'vs2017-win2016'
#    vmImage: 'Ubuntu 16.04'
#    vmImage: 'macOS-10.13'

  variables:
    jarname: $(jarnameVar) # System.getenv("jarname")

  steps:
  - script: ls
    displayName: ls command
  - task: Maven@3
    displayName: Maven Package
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      goals: 'clean install -Dhttp.keepAlive=false -DskipTests=true -Dmaven.wagon.http.pool=false'
#      goals: 'eclipse:clean prepare-package'
#      goals: 'clean -DskipTests=true package'
#      goals: 'clean test -DsuiteFile=testng-groups.xml'

  - script: ls
    displayName: ls
  - script: ls target/
    displayName: ls 'target' foler command
  - script: java -jar target/$(jarname) $(options)
#  - script: java -jar target/$(jarname) --xml testngTogether.xml --cl TestWatchCoMainPage --pr=name=JAR
#  - script: java -jar target/$(jarname) --cl TestWatchCoMainPage --pr=name=JAR
    displayName: java -jar on $(vmImageVar)
  - script: mvn allure:report
    displayName: allure
  - script: mvn site
    displayName: site

#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'artifactName'
#      targetPath: '$(System.DefaultWorkingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      name: 'drop'

