# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


jobs:
- job: PopoTestPageFlow
  pool:
    vmImage: 'vs2017-win2016'
#    vmImage: 'Ubuntu 16.04'

  variables:
    jarname: 'flow-page-1.0-shaded.jar'

  steps:
  - script: ls
    displayName: ls command
  - task: Maven@3
    displayName: Maven Package
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      goals: 'clean install -U'
#      goals: 'eclipse:clean prepare-package'
#      goals: 'clean -DskipTests=true package'

  - script: ls
    displayName: ls command
  - script: ls target/
    displayName: ls 'target' foler command
  - script: java -jar target/$(jarname) --xml testng.xml
#  - script: java -jar target/$(jarname) --xml testngTogether.xml --cl TestWatchCoMainPage --pr=name=JAR
#  - script: java -jar target/$(jarname) --cl TestWatchCoMainPage --pr=name=JAR
    displayName: java -jar

#  - task: PublishBuildArtifacts@1
#    displayName: Publish Build Artifacts
#    inputs:
#      PathtoPublish: '$(System.DefaultWorkingDirectory)'
#      name: 'drop'

